const eta=.5,r6=n=>Number(n.toFixed(6)),sigmoid=z=>1/(1+Math.exp(-z));
let hiddenCount=2,activation="sigmoid",revealed=0,active=1;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const base=[{w1:.15,w2:.20,b:.10,v:.30},{w1:-.10,w2:.05,b:-.05,v:-.25},{w1:.08,w2:-.12,b:.02,v:.18}],clone=p=>p.map(q=>({...q}));
function act(z){return activation==="sigmoid"?sigmoid(z):activation==="tanh"?Math.tanh(z):activation==="atan"?Math.atan(z):activation==="relu"?Math.max(0,z):z}function deriv(z){return activation==="sigmoid"?sigmoid(z)*(1-sigmoid(z)):activation==="tanh"?1-Math.tanh(z)**2:activation==="atan"?1/(1+z*z):activation==="relu"?(z>0?1:0):1}
function forward(p,x1,x2,y){const z=p.map(q=>q.w1*x1+q.w2*x2+q.b),h=z.map(act),zo=p.reduce((s,q,i)=>s+q.v*h[i],0)+(p.bo||.05),yh=act(zo);return{z,h,zo,yh,loss:.5*(y-yh)**2}}
function train(p,x1,x2,y){const f=forward(p,x1,x2,y),do_=(f.yh-y)*deriv(f.zo),dh=f.z.map((z,i)=>do_*p[i].v*deriv(z)),q=clone(p);q.forEach((u,i)=>{u.w1-=eta*dh[i]*x1;u.w2-=eta*dh[i]*x2;u.b-=eta*dh[i];u.v-=eta*do_*f.h[i]});q.bo=(p.bo||.05)-eta*do_;return q}
function rows(p,x1,x2,y){const f=forward(p,x1,x2,y),n=v=>r6(v).toFixed(6),a=[];p.forEach((q,i)=>{a.push([`z${i+1}`,`z${i+1} = w${i+1}1x₁ + w${i+1}2x₂ + b${i+1}`,`w${i+1}1=${n(q.w1)}, w${i+1}2=${n(q.w2)}, b${i+1}=${n(q.b)}, x₁=${x1}, x₂=${x2}`,`${n(q.w1)}(${x1}) + ${n(q.w2)}(${x2}) + ${n(q.b)}`,f.z[i],`Pre-activation of hidden unit ${i+1}`]);a.push([`h${i+1}`,`h${i+1} = ${activation}(z${i+1})`,`z${i+1}=${n(f.z[i])}`,`${activation}(${n(f.z[i])})`,f.h[i],`Activation of hidden unit ${i+1}`])});a.push(["zo","zₒ = Σ vᵢhᵢ + bₒ",p.map((q,i)=>`v${i+1}=${n(q.v)}, h${i+1}=${n(f.h[i])}`).join(", ")+`, bₒ=${n(p.bo||.05)}`,p.map((q,i)=>`${n(q.v)}(${n(f.h[i])})`).join(" + ")+` + ${n(p.bo||.05)}`,f.zo,"Output logit"]);a.push(["yh","ŷ = "+activation+"(zₒ)",`zₒ=${n(f.zo)}`,`${activation}(${n(f.zo)})`,f.yh,"Predicted y; actual y = "+y]);a.push(["E","E = ½(y − ŷ)²",`y=${y}, ŷ=${n(f.yh)}`,`0.5(${y} − ${n(f.yh)})²`,f.loss,"Sample loss"]);const do_=(f.yh-y)*deriv(f.zo);a.push(["do","δₒ = (ŷ − y)f′(zₒ)",`ŷ=${n(f.yh)}, y=${y}, f′(zₒ)=${n(deriv(f.zo))}`,`(${n(f.yh)} − ${y}) × ${n(deriv(f.zo))}`,do_,"Output error signal"]);f.z.forEach((z,i)=>{const d=do_*p[i].v*deriv(z);a.push([`d${i+1}`,`δ${i+1} = δₒv${i+1}f′(z${i+1})`,`δₒ=${n(do_)}, v${i+1}=${n(p[i].v)}, f′=${n(deriv(z))}`,`${n(do_)} × ${n(p[i].v)} × ${n(deriv(z))}`,d,`Hidden error signal ${i+1}`])});return a}
function total(){return 3*hiddenCount+4}function data(){const p0=clone(base.slice(0,hiddenCount));p0.bo=.05;const p1=train(p0,0,1,1),p2=train(p1,1,1,0);return{p0,p1,p2,r1:rows(p0,0,1,1),r2:rows(p1,1,1,0)}}
function render(id,data,count){$(id).innerHTML=data.map((r,i)=>`<tr class="${i<count?"revealed":""} ${i===count-1?"active-row":""}"><td>${i+1}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${Number(r[4]).toFixed(6)}</td><td>${r[5]}</td></tr>`).join("")}
function parameters(d){const keys=[];d.p0.forEach((_,i)=>keys.push(`w${i+1}1`,`w${i+1}2`,`b${i+1}`,`v${i+1}`));keys.push("bₒ");$("#parameter-table").innerHTML=keys.map(k=>{const get=p=>k==="bₒ"?p.bo:p[Number(k.match(/\d/)[0])-1][k[0]==="w"?(k[2]==="1"?"w1":"w2"):k[0]];return `<tr><td>${k}</td><td>${get(d.p0).toFixed(6)}</td><td>${get(d.p1).toFixed(6)}</td><td>${get(d.p2).toFixed(6)}</td></tr>`}).join("")}
function text(id,v){const e=$(id);if(e)e.textContent=v}
function updateGraph(c,calc,p){const f=forward(p,active===1?0:1,1,active===1?1:0),n=v=>v==null?"—":Number(v).toFixed(6);p.forEach((q,i)=>{text(`#w${i+1}1-value`,q.w1.toFixed(3));text(`#w${i+1}2-value`,q.w2.toFixed(3));text(`#h${i+1}-value`,c>=2*i+2?n(f.h[i]):"—");text(`#z${i+1}-value`,`z${i+1} = ${c>=2*i+1?n(f.z[i]):"—"}`);text(`#delta${i+1}-value`,`δ${i+1} = ${c>=2*hiddenCount+5+i?n(calc[2*hiddenCount+4+i][4]):"—"}`)});text("#zo-value",`zₒ = ${c>=2*hiddenCount+1?n(f.zo):"—"}`);text("#yhat-value",c>=2*hiddenCount+2?n(f.yh):"—");text("#loss-value",`E = ${c>=2*hiddenCount+3?n(f.loss):"—"}`);text("#deltao-value",`δₒ = ${c>=2*hiddenCount+4?n(calc[2*hiddenCount+3][4]):"—"}`);text("#graph-state-tag",`state ${c} / ${total()} · ${activation}`);[1,2,3].forEach(i=>["#node-h"+i,"#edge-x1-h"+i,"#edge-x2-h"+i,"#edge-h"+i+"-y","#edge-y-h"+i+"-back"].forEach(s=>$(s)?.classList.toggle("hidden-graph",i>hiddenCount)))}
function highlight(c){$$('.graph-current,.graph-edge-current,.graph-value-current').forEach(e=>e.classList.remove('graph-current','graph-edge-current','graph-value-current'));if(!c)return;if(c<=2*hiddenCount){const i=Math.ceil(c/2),edge=c%2;$(edge?`#edge-x1-h${i}`:`#node-h${i}`)?.classList.add(edge?'graph-edge-current':'graph-current');if(edge)$(`#edge-x2-h${i}`)?.classList.add('graph-edge-current');$(`#${edge?'z':'h'}${i}-value`)?.classList.add('graph-value-current')}else if(c===2*hiddenCount+1){for(let i=1;i<=hiddenCount;i++)$(`#edge-h${i}-y`)?.classList.add('graph-edge-current');$("#zo-value")?.classList.add('graph-value-current')}else if(c===2*hiddenCount+2){$("#node-output")?.classList.add('graph-current');$("#yhat-value")?.classList.add('graph-value-current')}else if(c===2*hiddenCount+3){$("#node-output")?.classList.add('graph-current');$("#loss-value")?.classList.add('graph-value-current')}else if(c===2*hiddenCount+4){for(let i=1;i<=hiddenCount;i++)$(`#edge-y-h${i}-back`)?.classList.add('graph-edge-current');$("#deltao-value")?.classList.add('graph-value-current')}else{const i=c-(2*hiddenCount+4);$(`#node-h${i}`)?.classList.add('graph-current');$(`#edge-y-h${i}-back`)?.classList.add('graph-edge-current');$(`#delta${i}-value`)?.classList.add('graph-value-current')}}
function update(){const d=data(),a=Math.min(revealed,total()),b=Math.max(0,Math.min(revealed-total(),total())),c=active===1?a:b,p=active===1?(a===total()?d.p1:d.p0):d.p1,calc=active===1?d.r1:d.r2;render("#trace-1",d.r1,a);render("#trace-2",d.r2,b);parameters(d);updateGraph(c,calc,p);highlight(c);const phase=c<=2*hiddenCount?"forward":c<=2*hiddenCount+3?"forward / loss":"backward signal";text("#state-step",`Step ${c} / ${total()} · ${phase}`);text("#sample-x",active===1?"(x₁, x₂) = (0, 1)":"(x₁, x₂) = (1, 1)");text("#sample-y",active===1?"actual y = 1":"actual y = 0");if(!c)["#state-equation","#state-values","#state-calculation","#state-result","#state-meaning"].forEach(x=>text(x,"—"));else{const r=calc[c-1];text("#state-equation",r[1]);text("#state-values",r[2]);text("#state-calculation",r[3]);text("#state-result",Number(r[4]).toFixed(6));text("#state-meaning",r[5])}text("#round-1-state",a===total()?"complete":a+" / "+total());text("#round-2-state",b===total()?"complete":b+" / "+total());text("#progress-label",revealed<=total()?`Round 1 · ${a} / ${total()} steps`:`Round 2 · ${b} / ${total()} steps`);text("#progress-percent",Math.round(revealed/(2*total())*100)+"%");$("#progress-bar").style.width=Math.round(revealed/(2*total())*100)+"%";$("#next-btn").disabled=revealed>=2*total();text("#phase-tag",phase);text("#coach-note",c?`Using ${activation} activation; its derivative is included in backpropagation.`:"Choose a configuration, then start with the first hidden pre-activation.")}
function show(n){active=n;$("#round-1").classList.toggle("hidden",n!==1);$("#round-2").classList.toggle("hidden",n!==2);$$('.round-tab').forEach(b=>{const on=Number(b.dataset.round)===n;b.classList.toggle('active',on);b.setAttribute('aria-selected',on)})}
$("#next-btn").addEventListener("click",()=>{revealed=Math.min(2*total(),revealed+1);if(revealed>total())active=2;update()});$("#round-btn").addEventListener("click",()=>{revealed=active===1?total():2*total();update()});$("#show-all-btn").addEventListener("click",()=>{revealed=2*total();show(1);update()});$("#reset-btn").addEventListener("click",()=>{revealed=0;show(1);update()});$$('.round-tab').forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.round))));$("#hidden-count").addEventListener("change",e=>{hiddenCount=Number(e.target.value);revealed=0;show(1);update()});$("#activation-select").addEventListener("change",e=>{activation=e.target.value;revealed=0;show(1);update()});update();
